@startuml

package "WebScraper" {
    [Walker] as w
    [Web Scraper] as ws
    [Blacklist] as bl
    [Image Downloader] as id
}

w ..> ws
ws .> bl
id ..> bl
'ws -> id
Website <.. ws: http(s)
Website <.. id: http(s)

database "PostgreSQL" {
    [document]
    [links]
    [pics]
    [blacklist]
}

ws ..> [document]
ws ..> [links]
ws ..> [pics]
bl ..> [blacklist]
id ..> [pics]
'id ..> [blacklist]

@enduml
