@startuml

hide circle
skinparam linetype ortho

entity documents {
    id: UUID <<generated>>
    --
    * url: varchar(1000)
    * downloaded_at: timestamp
    * content: text
    created_at: timestamp
    created_by: varchar(100)
}

entity links {
    id: UUID <<generated>>
    --
    * url: varchar(1000) <<UNIQUE INDEX>>
}

entity documents_to_links {
    id: UUID <<generated>>
    --
    * document_id: UUID <<FK>>
    * link_id: UUID <<FK>>
}

entity images {
    id: UUID <<generated>>
    --
    * url: varchar(1000) <<UNIQUE INDEX>>
    size: integer
    width: integer
    height: integer
    filename: varchar(1000)
}

entity documents_to_images {
    id: UUID <<generated>>
    --
    * document_id: UUID <<FK>>
    * image_id: UUID <<FK>>
}


documents ||--o{ documents_to_links
documents_to_links }|--|| links
documents ||--o{ documents_to_images
documents_to_images }|--|| images

@enduml
