@startuml

package "WebScraper" {
    [Walker] as w
    [Downloader] as ws
    [Image Downloader] as id
    [Repository] as r
}

w ..> ws
ws ..> r
'ws -> id
Website <.. ws: http(s)
Website <.. id: http(s)

database "PostgreSQL" {
    [document]
    [links]
    [images]
}

r ..> [document]
r ..> [links]
r ..> [images]

@enduml
